### PR TITLE
Release 4.2.1

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 4.2.1
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Release Test

### CODE REVIEW

**Comment by kpodemski** [comment]
Thanks @Progi1984 

Let's wait a bit for Daniel's PR 👍

**Review by matks — APPROVED** [review]
If I am not wrong the only behavior changing PRs for 4.2.1 are https://github.com/PrestaShop/gsitemap/pull/155 and https://github.com/PrestaShop/gsitemap/pull/150

**Review by kpodemski — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @Progi1984 

Thank you for your PR, I tested it and it works, 

Thank you

**Comment by matks** [comment]
Thank you everyone @Progi1984 and involved!

**Pull request merged**
