### PR TITLE
Standard URL support for gsitemap

### PR DESCRIPTION
**Pull request by l2affiki**
Hello, 
I've tested this code out and it seems to be working good.  This is my very first pull request, so any feedback would be very welcome!

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hi @l2affiki,

Thanks for your PR.
I've checked the module and it is already taking into account if the friendly URLs are activated or not. Also, the CDATA are necessary if you activate the accented URL. 
Don't hesitate to tell me if I misunderstood.

Best regards.

**Comment by l2affiki** [comment]
Hey Maxime,
thanks for the quick reply. I'm trying to make it so that this module works
with friendly-urls disabled, in addition to working with friendly-urls
enabled (which now seems to be the default).

The error occurs for me on a clean install of 1.6.0.14.  My steps are ...
1. install
2. disable friendly-urls
3. enable gsitemap (loads v3.0.5)
4. In the gsitemap config, disable all optional urls (to generate the
simplest sitemap possible)
5. generate sitemap

I've attached the sitemap which this process created.  Within it you can
see the first location is
http://localhost/ps_16014/tshirts/1-faded-short-sleeves-tshirt.html
    (friendly url = wrong, generates 404 as rewrites are currently not
being performed)

further down the first category url that occurs is
http://localhost/ps_16014/index.php?id_category=2&amp;controller=category
     (apache url = correct)

Let me know if you can or can't replicate.

From what I understand the link rewrite is hardcoded at line 373 because
the last argument is set to true.  This calls ...
Link->getProductLink() with $force_routes set to true, which calls
Dispatcher->getUrl() with $force_routes set to true,
At line 660 in Dispatcher, $force_routes is tested and if true, used to
build a friendly-url
     else  "// Build a classic url"





 will eventually be used to call the dispatchers

**Comment by maximebiloe** [comment]
Hello @l2affiki,

I've reproduced your issue and just made a PR (#21) to correct it.
It's only necessary to delete the params that forces the using of friendly URL because the Dispatcher will automatically check if it's activated or not.
So, let me close this PR.

Thanks for your help.
Regards.

**Comment by l2affiki** [comment]
Thanks @maximebiloe , that makes sense. I'm happy to help.  

About the cdata wrapper.  After making the first change, the product urls are created as such
`<![CDATA[
http://localhost/ps_16014/index.php?id_product=1&amp;controller=product
]]>`

I submitted a sitemap formatted this way to google webmaster tools and it gave me a 404 for every product url.  The problem seemed to be that the &amp; was not decoded by Google's indexer.  Within webmaster tools the urls were stored as `?id_product=1&amp;controller=product`.

After removing the cdata wrapper and resubmitting they were stored as 
`?id_product=1&controller=product`, and were no longer generating 404s.

See https://support.google.com/webmasters/answer/35653?hl=en for a quick run down of what their indexer expects.

This suggests that we should be using percent encoding on special characters.  From what I've gathered,  cdata is only designed to prevent xml reserved-chars from being parsed by an xml parser.  ( < > " & ' ).  At line 781 _addSitemapNode() is called.  Within it, $link is being passed through htmlspecialchars() transforming xml-reserved chars into their entity equivalents.  This should be sufficient for storing xml-reserved chars within the sitemap. cdata seems to undo the work of that encoding by preventing them from being decoded, and in turn presents an indexer with a non-existent url.

For special characters, it looks like we would need to percent encode on the path section of the url via a method such as rawurlencode(), while making sure to protect any reserved characters.

Let me know what you think. I'm not sure how to test this issue without a live site or a web-indexer to play with.

**Comment by maximebiloe** [comment]
Hi @l2affiki,

I just checked and if you turn off the friendly urls, the `<![CDATA[..]]` are not added for the url, only for the caption and title.
Here is what I get for a product URL :
`<loc>http://localhost/PrestaShop/index.php?id_product=6&amp;controller=product&amp;id_lang=1</loc>`
So the `&amp;` is interpreted by sitemap readers.

Best regards.

**Comment by l2affiki** [comment]
Hey @maximebiloe,
You are correct, I forgot I had pulled out the ternary at line 837
Cheers

**Pull request closed without merging**
