### PR TITLE
Use meta description instead of description

### PR DESCRIPTION
**Pull request by MathiasReker**

### CODE REVIEW

**Comment by MathiasReker** [comment]
@PierreRambaud Can you please check this ? :)

**Comment by MathiasReker** [comment]
Fix: https://github.com/PrestaShop/gsitemap/issues/67

**Comment by pvechi** [comment]
Hi @PierreRambaud and @MathiasReker this solution only covers the image caption for the category and not the product.  I believe we need to look at line 408 for a solution if we are going to replace short description of the meta description of the product.

**Comment by MathiasReker** [comment]
@pvechi could you pleaase try my fix and tell me what you think? :) See latest commit.

**Comment by PierreRambaud** [comment]
Thanks for your reactivity @MathiasReker ;)

**Comment by MathiasReker** [comment]
@marionf wdyt? :)

There are some issues in the module at the moment. It could be nice to have 4.0.1 released.

**Comment by PierreRambaud** [comment]
Woot, my bad @MathiasReker I on merge without checking the target branch.
Can you target the dev branch instead of master?

**Comment by PierreRambaud** [comment]
I did it for @MathiasReker  Sorry for the mistake

**Comment by MathiasReker** [comment]
Thank you @PierreRambaud

**Comment by pvechi** [comment]
Thanks @MathiasReker and @PierreRambaud all looks good. Sorry for MIA.

**Pull request merged**
