### PR TITLE
Deploy v4.1.0 of gsitemap

### PR DESCRIPTION
**Pull request by Quetzacoalt91**

### CODE REVIEW

**Comment by MathiasReker** [comment]
No new features has been introduces, only bug fixes. Don't you think the version should be 4.0.1 instead?

**Comment by Quetzacoalt91** [comment]
Some feature have been improved, and the number of modified files makes a new minor version more logical.

**Comment by MathiasReker** [comment]
@Quetzacoalt91 I do understand now. Thank you :)

**Comment by Quetzacoalt91** [comment]
Do not merge today, as we do not want the new version to be deployed during the week end.

**Pull request merged**
