### PR TITLE
[-] MO :  Bad protocol in ssl

### PR DESCRIPTION
**Pull request by massimonicoli**
Line 510: Image link for manufacturers in sitemap files with http even if https in enabled
Line 861: Sitemap links in sitemap index file with http even if https in enabled

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR.
I believe you need to test Configuration::get('PS_SSL_ENABLED_EVERYWHERE') too.

Regards

**Comment by massimonicoli** [comment]
Hi, updated the gsitemap.php.

Now, only if both PS_SSL_ENABLED & PS_SSL_ENABLED_EVERYWHERE are enabled then:
- image link for manufacturers in sitemap files start with https
- sitemap links in sitemap index file start with https

Otherwise:
- image link for manufacturers in sitemap files start with http
- sitemap links in sitemap index file start with http

I already tested both ways and they work fine.

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR and contribution.

Regards

**Comment by kolterox** [comment]
Gregory,

I failed to understand why this PR was merged so fast. Did you notice that a similar PR #8  (which fixes more bugs) was submitted 2 months ago?

Regards,

**Comment by gRoussac** [comment]
Hi,

Because I received a mail at noon I can fastly answer on what may be wrong about the second configuration key (even if i'm not in charge of this module) and because this is a small change I can read, check and merge without big tests and on which I can trust.

The first PR was probably not merged because it was not ok, probably because it misses the second conf key and because it affects a cron url, stores url etc and this will need further tests. Or maybe because nobody took the time to merge and test it.

I would be very pleased if you make a PR on supplier like it suggests too.

Best regards

**Comment by kolterox** [comment]
Sorry but from my point of view, it's a pretty ugly way to consider contributions.

If this PR do not respect your coding rules, do not pass the functionnal tests (can't be worst than not working properly like it is for now) or whatever other reason, it would have been respectful to take 2 minutes (probably one would have been far enough) to comment the PR.

About the miss of the second conf key argument, I can't take it. We're discussing about a 5 lines patch. Adding the missing key would'nt have been a big deal for a junior developer while merging this PR.

Regards,

**Comment by gRoussac** [comment]
Well then sorry for merging this then, I leave that developper comment and merge PRs on this module.

Regards

**Pull request merged**
