### PR TITLE
remove caption and title tags of the images

### PR DESCRIPTION
**Pull request by Uhor**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Google has stopped using the tags `<image:caption>, <image:geo_location>, <image:title>, <image:license>`, so we can delete that part from the code, making sitemap file lighter (good for big stores).
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | yes
| Fixed ticket? | -
| How to test?  | Just generate a new sitemap

Links: 
- [https://developers.google.com/search/docs/crawling-indexing/sitemaps/image-sitemaps#deprecated](url)
- [https://developers.google.com/search/blog/2022/05/spring-cleaning-sitemap-extensions](url)

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
@Uhor You need to remove one error from 1.7.8 phpstan config, then all good :-)

     Ignored error pattern #Parameter \#1 \$str of function strip_tags expects  
     string, array<string> given.# was not matched in reported errors.

**Review by Hlavtox — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Uhor** [comment]
Should I change the version?

**Comment by Hlavtox** [comment]
@Uhor Not needed, we can bump it later

**Review by M0rgan01 — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Uhor ,

Generated multiple sitemaps with different languages.
The tags `<image:caption>`, `<image:geo_location>`, `<image:title>` and `<image:license>` are not displayed anymore and I found no other issue.

LGTM ✅

**Comment by Hlavtox** [comment]
Good job everyone!

@Uhor Adrian, you can bump the version to 4.5.0 and we can do a release. ;-)

**Comment by Uhor** [comment]
> Good job everyone!
> 
> @Uhor Adrian, you can bump the version to 4.5.0 and we can do a release. ;-)

It's already merged and didn't bump the version. It's okay?

**Comment by Hlavtox** [comment]
Yes, PRs to develop branch don't have to bump a version, if they are not adding some upgrade scripts. You can do it in a separate PR. :-)

**Pull request merged**
