### PR TITLE
Fix wordings

### PR DESCRIPTION
**Pull request by eternoendless**
This PR uses the new translation system, thus bumping minimum compatibility to 1.7

### CODE REVIEW

**Comment by Mreker** [comment]
I compared your PR to my PR. The only diff is https://github.com/PrestaShop/gsitemap/pull/53/commits/bd49fda1fff69891e2ab28083e19e433cd1f777d

If you merge my PR, you can close this. Then there will be no conflicts :)

**Comment by PierreRambaud** [comment]
@Mreker @eternoendless is currently busy, he will have a check on monday :)

**Comment by Mreker** [comment]
This can be closed :-)

**Comment by eternoendless** [comment]
Thanks @Mreker

**Pull request closed without merging**
