### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by MathiasReker**
Just a few minor improvements

### CODE REVIEW

**Comment by MathiasReker** [comment]
WIP

**Comment by MathiasReker** [comment]
@PierreRambaud Consider to merge this PR as well :)

**Comment by MathiasReker** [comment]
Does this PR need QA?

**Comment by PierreRambaud** [comment]
Always need QA, always :D

**Comment by MathiasReker** [comment]
Safety first 😄

**Comment by MathiasReker** [comment]
Ping @marionf

**Comment by marionf** [comment]
Sorry @MathiasReker I was on the release tests last week
It's ok for this one :)

**Comment by Quetzacoalt91** [comment]
Thank you @MathiasReker

**Pull request merged**
